language: java
FROM openjdk:8-jdk-slim AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
                git \
                maven \
        && rm -rf /var/lib/apt/lists/*
WORKDIR GlobalSecretManager/src
#ADD pom.xml ./
RUN mvn package

FROM openjdk:8-jre-slim
COPY --from=builder GlobalSecretManager/target/GlobalSecretManager-0.0.1-SNAPSHOT.jar ./
CMD ["java", "-jar", "GlobalSecretManager-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080