language: java
services:
  - docker
env:
  global:
    - secure: "WgQDD4hQRazibTT+X+pMY8b17Lij5F2WXJkrBKJHXTzgqgpakKBJu9S3dyYF2nT4+56t8jO3wz0hW3Hr/9yJBw0zgLz1bfBmX56tWQvj/dxRqnBoReolKdrGNXizAwF8n2pcSpCFaVD07aaz+Wez+ZCX/crmQXId8886pyJJLfcUoe7KLXqOKdd/p15mKsSxIhRW9+KVBpX3TuCgnyASP8Ri0qO19f2xhgYWeBhP0QEgX1nTplK2siyZWJp7ZBCWwpHb8PN59a6BEsHWoDrBJNQA2VWn4YK2RsH5a/12+EgCji7BiPGzxVAKlnIsqQZrlHlaUEEAvw+g7kLcKO/hLTFW7l5DdazOlk0Na+I/0nVtDAOswFmD25TZXp9jeMnS8cs2niS8+c67RhJB4BF7pNNjwhfd6N8ndPzQ2fhOrL+Qicdy4XuBS9mzPMledk31ZbR1w0rBq6TYLvYDY8+VBbA4UlES0ZPeegxMFZ4t5DWAwkWJIKHeidt1iIVvujb58hBqB4ZdBnffhVL+ADsGT2gIF/PJdPMizu1p/47EoTtTK8aFP+IEqlt/8ZHCOfQSngHs15LDi5NuUz6PLgLrNBnAxq9GD3bNv0IublTY/YB71OBIiuMaAgYk3P2tHhC4iDwRzrzCXK3tMzcmbKqglVY9KdCGvlqQi/J620iFguk=" #DOCKER_EMAIL
    - secure: "DFUkQ+CASJTZ7eHrGKxIObH4TbhVxrdFEAztAwC3DzIZMNC9z893NwzPsM089s/cjiRe18Z0I4KhDlO0jYbH9Oix4ImsH6/Jh3rYro2ISOTqPAvOCk9XpoR2F38c3r5Q7cOkfWQbzqISzIT+2NJi3q9SAZuk1cGd9mWs/5iy2J61h5+eLWkzrCw4qDN8uw8fGweyVFDySzGlZRGPKsaiEiYlCSQgysLU8pD3jFqVKuCZq7wPyr5BdZ8A1pe74Ww25WAMpB3k6LhfrEz/oACNuEYkyiBvts4m4TLm0z79WqwxE/h2gFMyA2DQ4KG3hc8txCstnHTm6rru6uWYPLwecp7e1zWf9y/24x1C25MLKGdQr+3dl00TmfOeVZoICgeH2OCoM4/ggXBcy4WBcDLypDLWr/7AVVnA9niF9YSdUgUP1kXzNTsH69JkvSffADOlfsO5LB8/891I8m+i15tJW43OTbXSjW3Zu43Iddhe6+lUDd9Hu5B8skng3BtqAThkyZIIjArdjQnXaCI8GUk7jF/0DMgNkMuCxD4OKHwo3/hiWpdaUtBBT+cBcqHB8Qz8QyaVSK42CD7J3MjSbm+Kiv1p1/hdlX1M4IadIKZhCHnlb9ED6bSaOGC9qq+eeRJUPqfKKKSnHqLHKmyfyjRD820r+QjRSv1qo/KhV9WvfiI=" #DOCKER_USER
    - secure: "fhrKzgYMXPj7xMEki20x/8BBt80IEPpNYZ5Xj7nDdf38hGIlj1QYK9mFH+jMWDhGh+X3Vypj3/M/TR+zxzegRybJYtPpr5Ge1LQpY+0Xke/FiB7/SIBJ919/1+2MZu2K1OsFe5xh6D/rVjpXz8QvZdNK+1pBIq5LtZ8KjjUYdSDr2zD8kXaig/4CRnplq00B9Ub6wL0OiGmnZoBMWqiyC3SSqocRnti9sD17qo+eb7ijYQawwBTcbSuOF9xhk3FORQjSrHk/Qqb3oWgJiOE4GHn2MckoFVHv+ogmnBOlZhG3VVvMHHk9ONEbmDzAmrlmIcHLLIBWpfaMOm/kU1a70401AwQ7WWaeqXf7dvhBdCEstS0tlw57n7nVqMi/6vMMibOWvI0/t9rLxOmDBV1uAppp3eb6joayUdQr+6hkdaNhstW3Id1JQVQFGsspYfrttxY5kqCGDqMln6yUnvOZ5gbya2Vz/k1grgq0k++/4IfdR6d2qcVR/ySnzzxfAA40ASojSb+KGnkwmiNR/MubbTyNEUxXvNrwMdO2+Kc8M64noKMT4H6aegw9JM4qx9nAxGjv3Wvpqd8C+9j30ArsEyQSYw2Qun5+nP0mt3YOXy9R1Hu9NX61mL28EsP1M9fg1kI6mVil2aoX4G0RXSm41hxVmbTSriRj54+y4eO86OA=" #DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8}

    after_success:
      - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - export REPO=NicolaBilinats/globalsecretmanager
      - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
      - docker build -f Dockerfile -t $REPO:$COMMIT .
      - docker tag $REPO:$COMMIT $REPO:$TAG
      - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
      - docker push $REPO

branches:
  only:
  - master

